
val_datasets: 
  Amstertime: "/home/oliver/datasets_drive/vpr_datasets/VPR-datasets-downloader/datasets/amstertime"
  Pitts30k: "/home/oliver/datasets_drive/vpr_datasets/VPR-datasets-downloader/datasets/pitts30k"
  Tokyo247: "/home/oliver/datasets_drive/vpr_datasets/VPR-datasets-downloader/datasets/tokyo247"
  Eynsham: "/home/oliver/datasets_drive/vpr_datasets/VPR-datasets-downloader/datasets/eynsham"
  SVOX: "/home/oliver/datasets_drive/vpr_datasets/VPR-datasets-downloader/datasets/svox"
  MSLS: "/home/oliver/datasets_drive/vpr_datasets/msls"
