pipeline:
  - step: ReadGsvCities
    params:
      gsv_cities_path: /home/oliver/datasets_drive/vpr_datasets/gsv-cities
      cities: 
        - London 
        - Boston
        - WashingtonDC
        - Osaka
        - Rome
        - Chicago
        - Medellin
        - PRS

  - step: Embeddings 
    params:
      model_name: EigenPlaces
      batch_size: 128
      num_workers: 12

  - step: MultiSimilarityHardness
    params: 
      batch_size: 256

  - step: ConfusionMixer
    params:
      rate: 0.0

  - step: Sampler 
    params:
      min_instances_per_class: 4
  
      