ReadGsvCities:
  gsv_cities_path: /Users/olivergrainge/datasets/gsv-cities
  cities:
    - Rome

RandomClassSampler:
  num_classes: null
  num_instances_per_class: null
  num_instances: 28
  min_instances_per_class: null

Embeddings:
  model_name: EigenPlaces
  batch_size: 32
  num_workers: 4

ComputeHardness:
  batch_size: 32
  margin: 0.1

