CorePlaceModel: 
  arch_name: resnet50gem
  pretrained: True
  desc_dim: 512
  learning_rate: 0.001
  weight_decay: 0.0001
  recallatks: 
    - 1


CorePlaceDataModule: 
  dataconfig: registry/datasets/test_curate.pkl
  image_size: 128
  batch_size: 4
  num_workers: 0
  num_images_per_place: 4
  val_dataset_names: 
    - Sped 
    - Amstertime



Trainer: 
  max_steps: 10000 
  gradient_clip_val: 1.0
  num_sanity_val_steps: 0
  #limit_val_batches: 10
  limit_train_batches: 10

Logger: True 
Checkpoint: True

