pipeline:
  - step: ReadGsvCities
    params:
      gsv_cities_path: /home/oliver/datasets_drive/vpr_datasets/gsv-cities
      cities: 
        - London 
        - Boston
        - WashingtonDC
        - Osaka
        - Rome
        - Chicago
        - Medellin
        - PRS

  - step: Entropy
    params: 
      image_size: 224

  - step: Sampler
    params:
      sampling_field: entropy
      min_instances_per_class: 6
      instance_percentile:
        - 5
        - 100

  - step: Sampler  
    params:
      min_instances_per_class: 6
      num_classes: 5000
      num_instances_per_class: 6
      